setting:
  basicSetting:
    completionTone: 1
    colorLog: 1
    logOutFileSw: 1
    logLevel: "INFO"
    logModel: 0
  emailInform:
    sw: true
    SMTPHost: "192.168.31.249"
    SMTPPort: "465"
    userName: "1740077809@keaident.cn"
    password: "Pjd20050611"
  aiSetting:
    aiType: "DEEPSEEK"
    aiUrl: "https://api.deepseek.com"
    model: "deepseek-v4-flash"
    API_KEY: " "
  apiQueSetting:
    url: "http://192.168.31.184:8083"
users:
  - accountType: "XUEXITONG"
    url: ""
    account: "15378913794"
    password: "M12345678"
    isProxy: 0
    informEmails:
      - "1740077809@qq.com"
      - "2149517810@qq.com"
      - "0002@keaident.cn"
    coursesCustom:
      studyTime: "10-30"
      shuffleSw: 0
      cxNode: "10"
      cxChapterTestSw: 1
      cxWorkSw: 1
      cxExamSw: 0
      videoModel: 3
      autoExam: 1
      examAutoSubmit: 1
      excludeCourses: []
      includeCourses: []
