setting:
  basicSetting:
    completionTone: 1
    colorLog: 1
    logOutFileSw: 1
    logLevel: 'INFO'
    logModel: 0
  emailInform:
    sw: true
    SMTPHost: '192.168.31.249'
    SMTPPort: '465'
    userName: '1740077809@keaident.cn'
    password: 'Pjd20050611'
  aiSetting:
    aiType: 'DEEPSEEK'
    aiUrl: ''
    model: 'deepseek-v4-flash'
    API_KEY: 'sk-bb925b880610426eb977825e163eb345'
  apiQueSetting:
    url: 'http://192.168.31.184:8083'
users:
  - accountType: 'XUEXITONG'
    url: ''
    account: '19074795722'
    password: 'Sjt18727080647.'
    isProxy: 0
    informEmails:
      - '1740077809@qq.com'
      - '2149517810@qq.com'
      - '0002@keaident.cn'      
    coursesCustom:
      studyTime: '10-30'
      shuffleSw: 0
      cxNode: '5'
      videoModel: 3
      autoExam: 1
      cxChapterTestSw: 1
      cxWorkSw: 1
      cxExamSw: 0
      examAutoSubmit: 1
      excludeCourses: []
      includeCourses:
        - '形势与政策（二）/(四)（2025-2026-2）'
        - '24古代汉语（二）'

